#title in header
title: "â¬… Click Here"

#main info
#owner
owner: "slc3a2"
email: slc3a2@gmail.com
info: "A web developer from China ğŸ‡¨ğŸ‡³"
#description
desc: "ğŸ‘‹ This is slc3a2. welcome. here is just to record some fun ğŸ˜"

#menu
menu:
  My Application: /myApplication
  Sponsor: /sponsor
  # About: /About

#index/main page max show posts (in number)
max_post: 10

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/slc3a2
# linkedin: https://linkedin.com/in/adisaktijrs
# twitter: https://twitter.com/adisaktijrs
# instagram: https://instagram.com/adisaktijrs
stackoverflow: https://leetcode.cn/u/slc3a2

# Misc
nanobar: /js/nanobar.min.js
switch_light: ğŸŒ
switch_dark: ğŸŒš

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io

mathjax:
  enable: true
  cdn: https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-AMS-MML_HTMLorMML

google_analytics: 'G-52Y2B2P1QW'
